# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    application:
        name: Slowly Changing Dimensions POC Spring Boot Application
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML


endpoints:
 sensitive: true
 health:
   enabled: true
   sensitive: false
 shutdown:
   enabled: true
   
management:
 context-path: /manage
 security:
  enabled: false

security:
    basic:
        enabled: false

# ===================================================================
# Slowly Changing Dimensions POC Spring Boot Application service specific properties
# ===================================================================
foundation:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 31
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    security:
          rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: 7799f2232eb3b06afc2aeaa18822d8ba3f48503d
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: adp
        logs: # report metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    #Application Specific props
    service:
        client :
            activeAgeInYears : 3
    
# ===================================================================
# Tomcat Startup properties
# ===================================================================
server:
    port: 8081
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto
    contextPath: /poc
    
